version: 2
updates:
  # Git Packages
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    assignees:
      - Sirherobrine23
    schedule:
      interval: "daily"

  # Github Actions 
  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - Sirherobrine23
    schedule:
      interval: "daily"

  # Nodejs
  - package-ecosystem: "npm"
    directory: "/"
    assignees:
      - Sirherobrine23
    schedule:
      interval: "daily"
